defold/extender

- server/docker-base/Dockerfile
> Updated to use iPhoneOS 13.5, and Xcode 11.5

- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/ManifestMergeTool.java
> Check for platform "osx"

- server/manifestmergetool/build.gradle
- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/InfoPlistMerger.java
- server/manifestmergetool/src/test/java/com/defold/manifestmergetool/ManifestMergeToolTest.java
More info about the issue is available here https://github.com/defold/defold/issues/5165
This issue is similar to the issue we had in `bob` earlier: https://github.com/defold/defold/issues/4977
Current result:
> Issue-5165 Manifest merge tool can't merge arrays in plist

- server/src/main/java/com/defold/extender/Extender.java
> Include assets folders from resolved dependencies

- server/src/main/java/com/defold/extender/Extender.java
> Default to use of jetifier/androidx

- server/manifestmergetool/build.gradle
> Updated to newer version of the Android manifest merge tool

- server/src/main/java/com/defold/extender/WebSecurityConfig.java
- server/src/main/java/com/defold/extender/services/UserUpdateService.java
And immediately also update the users on creation
> Changed the way the UserUpdateService is initialized

- README_RELEASE.md
- server/scripts/publish-darwin-stage.sh
- server/scripts/standalone/publish-standalone.sh
- server/src/main/resources/application-production.yml
- server/src/main/resources/application-stage.yml
- server/src/main/resources/application-standalone-stage.yml
Separate service scripts so multiple services can run on a single machine
> Darwin stage setup

- server/docker-base/Dockerfile
- server/scripts/standalone/setup-standalone-server.sh
> Updated to XCode 13, iOS 15 and macOS 12

- client/build.gradle
- client/src/main/java/com/defold/extender/client/ExtenderClient.java
- client/src/test/java/com/defold/extender/client/ExtenderClientTest.java
This PR should be considered in combination with https://github.com/defold/defold/issues/6411
> Added option to specify additional headers to extender client

- server/docker-base/Dockerfile
Issue:
https://github.com/defold/test-sdk/actions/runs/3309355807/jobs/5462452441
> Added new alias for WlanTypes.h (Win32)

- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
Sub specs inherit flags and defines from the parent pod spec.
This PR also handles the `default_subspec` option.
Fixes #277
> Cocoapod subspecs must inherit attributes from the parent spec

- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
This change will make sure that only podfiles for the current platform are resolved.
Fixes #273
> Only resolve pods for the platform that is built

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
> Set compiler flags based on values in pod_target_xcconfig

- server/scripts/publish-darwin-prod.sh
- server/scripts/publish-darwin-stage.sh
- server/scripts/publish-xcloud-prod.sh
- server/scripts/publish-xcloud-stage.sh
- server/scripts/run-standalone-local.sh
- server/scripts/standalone/publish-standalone.sh
> Removed dependency on tools.sh

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
- server/src/main/java/com/defold/extender/services/GradleService.java
Client side: https://github.com/defold/defold/pull/7596/files
> Make sure gradle uses right Android SDK

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
> Add support for compiling plain c

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/FrameworkUtil.java
Dynamic frameworks should be embedded into the final application bundle. This PR identifies such frameworks and returns them with the build results to the client.
Fixes #274
> Embedd dynamic frameworks

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/FrameworkUtil.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
> Handle static libraries in frameworks

- server/docker-base/template.gradle.properties
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ExtenderUtil.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
> Handle static libraries in pods

- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
> Problem compiling YandexMobileAds

- server/docker-base/Dockerfile
Removed Mono since the extension-switch now invokes the locally installed tools
> Removed NSDK 14.3

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
Changed the way source and header files are added.
Fixes #306
> Facebook SDK for iOS not building with other extensions

- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
> Strip bitcode from framework libs

- server/scripts/standalone/service-standalone.sh
- server/scripts/standalone/setup-standalone-server.sh
- server/src/test/java/com/defold/extender/ExtenderTest.java
- server/test-data/compile.sh
Related PR:
https://github.com/defold/defold/pull/8364
> Updated to XCode 15.1 for the Darwin server

- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/metrics/MetricsWriter.java
- server/src/test/java/com/defold/extender/metrics/MetricsWriterTest.java
> Use long type for handling request body size.

- server/src/main/java/com/defold/extender/services/DefoldSdkService.java
Also added xbox download links
> Added stable download links for consoles

- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
> Fix platform version regex to handle osx

- server/docker-base/Dockerfile
Relates to https://github.com/defold/defold/issues/6259
> Add emscripten 3.1.55.

- server/src/main/java/com/defold/extender/Extender.java
Removed a lot of repeated code
> Cleaned up template and code execution

- server/docker-base/Dockerfile
Should be merged together with https://github.com/defold/defold/pull/9015
> Update Android SDK to version 34.0.0

- server/scripts/standalone/service-standalone.sh
- server/scripts/standalone/setup-standalone-server.sh
- server/src/test/java/com/defold/extender/ExtenderTest.java
Related PR https://github.com/defold/defold/pull/9049
Fix https://github.com/defold/extender/issues/388
> Updated to Xcode 15.4, iOS SDK 17.5 and macOS SDK 14.5 for the Darwin server

- .github/workflows/dockerimage.yml
Cleanup `28GiB` with  https://github.com/jlumbroso/free-disk-space
Now we have about `45G` free
> Cleanup disk space

- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/remote/RemoteEngineBuilder.java
Remove unnecessary cache upload operation. All cache upload happened in `ExtenderController` handlers.
> Remove excessive cache operations.

- server/html_data/index.html
- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/remote/RemoteEngineBuilder.java
- server/src/main/java/com/defold/extender/services/HealthReporterService.java
* Added special service which collects all information about remote builder status, accumulate per platform and return as JSON.
* Added status page ready-to-deploy on Github pages.
Status page example:
> Health report

- server/html_data/index.html
- server/src/main/java/com/defold/extender/services/HealthReporterService.java
* Fix Nan in index.html (wrong calculation for total operational builder)
* Add connection timeout configuration in HealthReporter. Otherwise in case of suspended VMs we spend lots of time to reach connection timeout and request status of next builder.
> Add connection timeout in HealthReporterService. Fix Nan in status page.

- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/metrics/MetricsWriter.java
- server/src/main/java/com/defold/extender/services/DataCacheService.java
* Fix download cache size metric value.
* Unify information about download/upload caches.
* Add metrics to track download/upload cache file count.
> Fix download cache size metric value.

- server/build-docker.sh
- server/docker/Dockerfile.nssdk.1832-env
- server/docker/Dockerfile.ps5.9000-env
- server/docker/docker-compose.yml
> Update consoles sdks

- .github/workflows/application-build.yml
- .github/workflows/docker-env-build.yml
Accumulate PRs from dependabot.
> Update gh deps

- client/build.gradle
- server/build.gradle
- server/manifestmergetool/build.gradle
Compilation of all dependabot reports.
> Update java deps

- server/src/main/java/com/defold/extender/ExtensionManifestValidator.java
Add new whitelisted app manifest field
Relates to https://github.com/defold/defold/issues/8775, https://github.com/defold/defold/issues/8774
> Add more whitlisted options

- .gitignore
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
* Add launch tasks
* Add list of recommended extensions.
Relates to #467
> Add VSCode workspace.

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
This issue fixes issues when building for instance the Yandex SDK
Fixes #403
> Fix issues building certain combinations of pod dependencies

- .github/workflows/docker-env-build.yml
- server/build-docker.sh
- server/docker/docker-compose.yml
Retag private Docker images after registry split.
> Retag private docker images.

- server/scripts/standalone/setup-standalone-env.sh
> Fix Zig arch detection

- server/build.gradle
- server/docker/common-services.yml
* Fix issue with common-io exception
* Fix running docker compose when no DYNAMO_HOME is set.
> Fix issue with common-io exception

- .gitignore
- README_DEBUGGING.md
- server/docker/common-services.yml
- server/scripts/debug_defoldsdk.py
Fix DYNAMO_HOME handling in Docker environment.
> Fix documentations in area of debugging.

- .vscode/launch.json
- server/build.gradle
- server/scripts/standalone/service-standalone.sh
- server/src/test/java/com/defold/extender/remote/RemoteEngineBuilderTest.java
Add missed parameters to launch.json.
Fix standalone script with latest changes.
> Fix Extender tests.

- server/src/main/java/com/defold/extender/Extender.java
This change copies the resources per pod to subfolders to avoid duplicate files, for example when more than one pod has a PrivacyInfo.xcprivacy file defined among its resources.
Also included in this change is that the resources are returned to the client for further processing (for instance resource bundles).
Fixes #500
> Copy resources per pod

- server/build.gradle
- server/src/main/resources/application.yml
* Add cloud logging dependency to enable push logs to GCP.
* Add micrometrics prometheus to enable scrap metrics from application.
> Improve logging and metrics collection for external instances

- server/README.md
- server/build-docker.sh
Found some documentation issues
Also fixed the build-docker.sh to make it easier to pass in what things to install rather than commenting out bits that I do not have.
> Fixes while trying to use extender

- server/build-docker.sh
- server/docker/Dockerfile.ps4.12000-env
- server/docker/docker-compose.yml
Apparently, our current 11 version is already out-of-date
> Added support for PS4 SDK 12

- server/configs/application-local-dev-app.yml
- server/docker/docker-compose.yml
Removed old unused emsdk, nssdk, winsdk and ps sdk
> Added ps4-12000 and ps5-10000 to local docker builds

- .github/workflows/application-build.yml
- server/docker/common-services.yml
- server/scripts/start-test-server.sh
Added healthcheck command for test containers. Add uploading of test results.
> Added healthcheck for test containers

- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
- server/src/test/java/com/defold/extender/services/CocoaPodsServiceTest.java
- server/test-data/podfiles/regular.Podfile
- server/test-data/podfiles/with_comments.Podfile
- server/test-data/podfiles/wrong.Podfile
Fixed problem in Podfile parsing.
Added tests for Podfile parsing.
Fixes #546
> Fix issue with Podfile parsing. Add tests.

- server/README_METRICS.md
- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/metrics/MetricsWriter.java
- server/src/test/java/com/defold/extender/ExtenderTest.java
* Add counter metrics with build target type.
* Create Extender via builder class to eliminate lost of constructor parameters.
Fixes #559
> Add counter metrics with build target type.

- .github/workflows/application-build.yml
- server/build-docker.sh
- server/docker/Dockerfile.android-env
- server/docker/Dockerfile.android.ndk25-env
- server/docker/Dockerfile.base-env
- server/docker/Dockerfile.emsdk.2011-env
- server/docker/Dockerfile.emsdk.3155-env
- server/docker/Dockerfile.emsdk.3165-env
- server/docker/Dockerfile.linux-env
- server/docker/Dockerfile.nssdk.1532-env
- server/docker/Dockerfile.nssdk.1753-env
- server/docker/Dockerfile.nssdk.1832-env
- server/docker/Dockerfile.ps4.10500-env
- server/docker/Dockerfile.ps4.11000-env
- server/docker/Dockerfile.ps4.12000-env
- server/docker/Dockerfile.ps5.10000-env
- server/docker/Dockerfile.ps5.8000-env
- server/docker/Dockerfile.ps5.9000-env
- server/docker/Dockerfile.wine-env
- server/docker/Dockerfile.winsdk.2019-env
- server/docker/Dockerfile.winsdk.2022-env
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/DefoldSdkService.java
- server/src/main/resources/template.gradle.properties
- server/test-data/jars/build.sh
- server/test-data/sdk/a/defoldsdk/share/java/build.sh
I just changed the code, do I need to test it? how?
> Update Java version to JDK 21.0.5+11

- server/src/main/java/com/defold/extender/services/GCPInstanceService.java
- server/src/main/java/com/defold/extender/services/HealthReporterService.java
* Fix incorrect condition.
* Check for 'STAGING' state (instance is starting)
> Fix service state confition.

- client/build.gradle
- client/src/test/java/com/defold/extender/client/ExtenderClientTest.java
> Migrate client tests to JUnit5.

- server/manifestmergetool/build.gradle
- server/manifestmergetool/src/test/java/com/defold/manifestmergetool/ManifestMergeToolTest.java
Migrate manifest merge tool tests to JUnit5.
Part of #565
> Migrate manifestmergetool tests to JUnit5.

- server/src/main/java/com/defold/extender/builders/CSharpBuilder.java
This reverts commit 1a21296f953eeceb87ac704c946a429b90aa2930.
> Readded temporary hack for Dotnet 10 prerelease version

- client/src/main/java/com/defold/extender/client/ExtenderClient.java
- client/src/test/java/com/defold/extender/client/ExtenderClientTest.java
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/ExtenderUtil.java
- server/src/main/java/com/defold/extender/WebSecurityConfig.java
- server/src/main/java/com/defold/extender/remote/RemoteEngineBuilder.java
- server/src/test/java/com/defold/extender/ExtenderTest.java
- server/src/test/java/com/defold/extender/IntegrationTest.java
- server/src/test/java/com/defold/extender/remote/RemoteEngineBuilderTest.java
* Removed synchronous build implementation from Extender
* Removed synchronous build implementation from Extender's client
* Commented all `RemoteEngineBuilder` tests (need rework) https://github.com/defold/extender/issues/619
Fixes #616
> Remove synchronous build endpoint.

- server/build.gradle
- server/src/test/java/com/defold/extender/ExtenderTest.java
- server/test-data/sdk/a/defoldsdk/extender/build.yml
* Update jar test (fix after add meta-inf files https://github.com/defold/extender/pull/607)
* Update test `build.yml`
* Read environment variable from env vars.
* Fix build from command line (missed annotation processor for lombok).
> Fix build (add annotationProcessor for lombok). Update tests.

- .github/workflows/docker-env-build.yml
- server/README.md
- server/build-docker.sh
- server/configs/application-local-dev-app.yml
- server/configs/application-test-app.yml
- server/docker/Dockerfile.base-env
- server/docker/docker-compose.yml
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/WebSecurityConfig.java
- server/src/main/java/com/defold/extender/builders/CSharpBuilder.java
- server/src/test/java/com/defold/extender/IntegrationTest.java
> Support arm64 build

- .gitignore
- .idea/misc.xml
- .idea/modules.xml
- .idea/runConfigurations/Attach_to_java_process_inside_docker.xml
- .idea/runConfigurations/Run_standalone_Extender.xml
- .idea/vcs.xml
- README.md
- build.gradle
- client/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- server/build.gradle
- server/manifestmergetool/build.gradle
- server/settings.gradle
- settings.gradle
* Added IntelliJ IDEA projects settings (with preconfigured run tasks)
* Updated Gradle version for development because JDK21 requires at least Gradle 8.5 (it doesn't affect Gradle implementation inside Docker image)
Fixes #687 
Fixes #592
> Setup IntelliJ IDEA

- server/src/main/java/com/defold/extender/cache/GCPDataCache.java
* Added check for cache entry creating time.
* Skipped update cache entry if update was done less than 1 day ago
Fixes #693
> Fix cache entry update rate limit

- server/src/main/java/com/defold/extender/services/GCPInstanceService.java
> Speedup maintenance mode

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/cocoapods/PodSpecParser.java
- server/src/main/java/com/defold/extender/services/cocoapods/PodUtils.java
- server/src/main/java/com/defold/extender/services/cocoapods/ResolvedPods.java
- server/src/test/java/com/defold/extender/services/cocoapods/CocoaPodsServiceTest.java
- server/test-data/pod_specs/AXPracticalHUD.json
* Handle regex pattern from Pod resources section
* Added test for PodSpec parsing
Fixes #296
> Handle glob pattern from Pod resources section

- server/src/main/java/com/defold/extender/services/cocoapods/CocoaPodsService.java
- server/src/main/java/com/defold/extender/services/cocoapods/PodUtils.java
- server/src/test/java/com/defold/extender/services/cocoapods/PodUtilsTest.java
> Added pod name sanitizing

- server/build-docker.sh
- server/configs/application-local-dev-app.yml
- server/docker/Dockerfile.emsdk.406-env
- server/docker/docker-compose.yml
- server/src/test/java/com/defold/extender/IntegrationTest.java
> Added emsdk 4.0.6 docker image

- server/README.md
- server/build-docker.sh
> Added flag to skip arm64 docker image build

- server/src/main/java/com/defold/extender/Extender.java
Pass available processors to emit swift header and emit swift module commands
Related PR https://github.com/defold/defold/pull/10969
Fixes #583
> Parallelize swift header and module generation
