defold/extender

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ProcessExecutor.java
My game has a lot of C++ source files. Extender compiles C++ files one at a time, so every small change in the source code requires about 40-50 seconds to build. That's a lot of time!
This pull request adds a parallel compilation for C/C++ files, and the code uses all available CPU cores/threads. I suppose that it should utilise a single thread by default if only you didn't specify ENV variable with a different setting.
These changes are an example of how this can be done. If you decide to accept this pull request, I will polish it according to your requirements.
**Now Extender builds the game in 10 seconds on my 8-core PC.
> Add a parallel compilation for C/C++ files

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/PlatformConfig.java
- server/src/main/java/com/defold/extender/TreePrinter.java
This will allow us to send back the compiled resources to the client for use in the AAB build while at the same time getting R.java files with resource ids exactly matching the generated resources.
> Use aapt2 to compile android resources and generate R.java files

- server/docker-base/Dockerfile
- server/docker-base/template.build.gradle
- server/docker-base/template.gradle.properties
- server/docker-base/template.local.properties
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/ExtensionManifestValidator.java
- server/src/main/java/com/defold/extender/services/GradleService.java
- server/src/test/java/com/defold/extender/ExtenderTest.java
Migration to Android X will happen if the `jetifier` property is set in the app.manifest:
```
armv7-android:
context:
excludeLibs: []
excludeJars: []
excludeSymbols: []
symbols: []
libs: []
linkFlags: []
jetifier: true
```
> Use the Android Gradle plugin to migrate dependencies to Android X

- server/docker-base/Dockerfile
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ExtenderUtil.java
- server/src/main/java/com/defold/extender/PlatformConfig.java
- server/src/main/java/com/defold/extender/ProcessExecutor.java
Can build .proto files into engine + plugin source
Can generate a plugin .jar file
> Issue 5725: Added support for commonsrc+pluginsrc folders

- server/src/main/java/com/defold/extender/WebSecurityConfig.java
We can build ios for armv7 without authentication because there is misprint in endpoint name.
> Fix misprint in ios build endpoint name when configure web security.

- server/build.gradle
Because of dependency duplication extender starts inside Apache Tomcat, not inside Eclipse Jetty. These bug was introduced when spring boot were updated (https://github.com/defold/extender/commit/38d045ba2123eae178cc52eb6130cad5198c2637).
These fix remove dependency duplication. Now extender runs inside Jetty.
> Remove dependency duplication. Now extender start inside Jetty not inside Tomcat.

- server/build.gradle
https://spring.io/blog/2022/03/31/spring-boot-2-6-6-available-now
> Update Spring boot to 2.6.6 (fix CVE-2022-22965).

- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/ManifestMergeTool.java
- server/manifestmergetool/src/test/java/com/defold/manifestmergetool/ManifestMergeToolTest.java
It is now possible to use a merge node marker in the AndroidManifest.xml to indicate that a tag added from a library dependency should be removed:
```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />
```
Previous extender versions did not enable this feature of the manifest merge tool and any attempt to use a merge node marker was ignored.
> Use merge node markers to remove Android manifest tags

- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/InfoPlistMerger.java
- server/manifestmergetool/src/test/java/com/defold/manifestmergetool/ManifestMergeToolTest.java
It is now possible to control if a key in the base Info.plist file should be replaced by a key in a plist file from an extension or not:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd" [ <!ATTLIST key merge (keep) #IMPLIED> ]>
<plist version="1.0">
<dict>
<key merge="keep">NSPhotoLibraryUsageDescription</key>
<string>This value will be kept even if an extension also provide a 'NSPhotoLibraryUsageDescription' key</string>
</dict>
</plist>
```
Note the new `[ <!ATTLIST key merge (keep) #IMPLIED> ]` section in the `<!DOCTYPE`!
Fixes #205
> Added merge node markers for Info.plist keys

- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ExtenderController.java
Async builds will now return the full build log when requesting the `/job_result`. The request previously only returned the stack trace of the error. The result (stack trace and log) will be written to the log file on the client.
Fixes #221
> Send build server logs on error

- server/src/main/java/com/defold/extender/Extender.java
This change automatically adds each resolved Android Gradle dependency containing resources as an extra package when linking resources using `aapt2`. This reduces or completely removes the need to specify `aaptExtraPackages` in `ext.manifest`.
Fixes defold/defold#6047
> Automatically create Android R.java files for all Gradle dependencies

- server/scripts/standalone/publish-standalone.sh
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
This PR also includes a fix for missing `env` in the context (this issue popped up after the big refactor @JCash did).
Fixes #262
> Handle non boolean values for requires arc option

- server/src/main/java/com/defold/extender/ExtenderUtil.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
There were two issues that I found during cocoapods integration testing:
1. When command `pod spec cat --regex ...` produce some additional output like 
```
Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
```
build failed with exception.
2. If pod spec has vendored_frameworks section under platform section - it ignores and produces linker error later. For example, UnityAds pod has following spec
```
{
"name": "UnityAds",
"version": "4.2.1",
"license": {
"type": "Unity License",
"file": "LICENSE"
},
"authors": {
"UnityAds": "itunes@unity3d.com"
},
"homepage": "https://unity3d.com/services/ads",
"summary": "Monetize your entire player base and reach new audiences with video ads.",
"platforms": {
"ios": "9.0"
},
"source": {
"http": …
```
> Fix cocoapods issues

- server/test-data/jars/build.sh
This script for creation test data is the only place where we use `android.jar` from `defoldsdk`. In all other places on extender we use one from SDK 
This is the first step for removing `android.jar` from `defoldsdk.zip`
> Remove usage of android.jar from `share` folder

- README_RELEASE.md
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
> Module support

- server/docker-base/Dockerfile
Related to https://github.com/defold/defold/pull/8218
> Add MSVC 2022 to Docker container

- server/src/main/java/com/defold/extender/remote/RemoteEngineBuilder.java
- server/src/main/resources/application.yml
This change increases the remote builder timeout from 4 to 20 minutes. This matches the timeout value set in ExtenderClient.
> Increased remote builder timeout from 4 to 20 min

- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/InfoPlistMerger.java
- server/manifestmergetool/src/test/java/com/defold/manifestmergetool/ManifestMergeToolTest.java
> Check plist array for duplication during manifest merge phase.

- build.gradle
- client/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- server/build.gradle
- server/docker-base/Dockerfile
- server/docker-base/template.build.gradle
- server/docker-base/template.gradle.properties
- server/manifestmergetool/build.gradle
- server/scripts/standalone/service-standalone.sh
* Update Gradle to 8.4
* Gradle android plugin to 8.2.1
* Update gradle wrapper that used for building to 8.4. 
* Update build scripts according to new version to Gradle.
* Change gradle docker plugin.
* Use jdk 17 to run gradle during Android build.
* Remove various workarounds with jdk certificates from Dokerfile.
Fixes #290.
> Update gradle/gradle android plugin version

- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/InfoPlistMerger.java
- server/manifestmergetool/src/test/java/com/defold/manifestmergetool/ManifestMergeToolTest.java
Problem: https://github.com/defold/test-sdk/actions/runs/7621676374/job/20758423122
These happened because of strict type cast (casted to String, need - Object).
Also I've added code to merge nested dictionaries inside array value. Here is an example:
base manifest
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>UISupportedInterfaceOrientations~ipad</key>
<array> 
<string>UIInterfaceOrientationPortrait</string>
<string>UIInterfaceOrientationPortraitUpsideDown</string>
</array>
<key>CFBundleURLTypes</key>
<array>
<dict>
<key>CFBundleTypeRole</key>
<string>Editor</string>
<key>CFBundleURLName</key>
<string>REVERSED_CLIENT_ID</string> …
```
> Fix ios plist merge for array types.

- server/scripts/standalone/setup-standalone-server.sh
Fixes #348 
Checks if the download folder is empty, and doesn't copy it to the platformsdk folder if so.
> Don't move empty folders to platformsdk folder. 

- server/src/main/java/com/defold/extender/Extender.java
It's needed in cases the extender runs on M1 machine to be able to use right `protoc` executable, see https://github.com/defold/defold/issues/8566#issuecomment-1985492430
> Detect if extender run on arm64 mac (m1/m2)

- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/AndroidManifestMerger.java
- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/HtmlMerger.java
- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/InfoPlistMerger.java
- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/ManifestMergeTool.java
- server/manifestmergetool/src/main/java/com/defold/manifestmergetool/PrivacyManifestMerger.java
- server/manifestmergetool/src/test/java/com/defold/manifestmergetool/ManifestMergeToolTest.java
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
This change will gather all `*.xcprivacy` files from upload directory and from resolved pods and merge them into a single `PrivacyInfo.xcprivacy` and send the merged file together with other output files to the client.
Fixes #354
> Merge privacy manifests and copy to build output

- server/build.gradle
- server/scripts/build.sh
Specify explicitly `--platform` flag helps avoid issue on Apple silicon (and other non-Intel archs) because by default Docker select ubuntu image according to host platform. It leads to error during building because of java and container arch mismatch.
> Add --platform flag to ensure use right arch for docker container.

- server/test-data/ext/lib/js-web/library_dummy.js
The same changes was made here https://github.com/defold/extension-html5/pull/2.
Probably it could be some problems depends on what Emscripten version will be used for testing.
> Update test data accodring to changes from extension-html5.

- server/build.gradle
- server/src/main/java/com/defold/extender/ProcessExecutor.java
I had issues on my mac to connect from Gradle to the Docker daemon. An update of the plugin solved it. I have not noticed any problems and I can now perform a full build with tests.
While testing I also had Gradle logging set to `debug` which will log **A LOT**. This resulted in `OutOfMemoryError` in ProcessExecutor.java while appending to a `StringBuilder`. I added a try-catch and truncate the log if this happens.
> Upgrade gradle docker plugin

- server/manifestmergetool/build.gradle
Exclude dependencies that used by Google team to work with repo/tools. It's not necessary for Manifest merge implementation. As bonus - remove packages with security issues.
> Exclude dependencies that not necessary for manifestmergetool.

- server/docker/Dockerfile.android-env
- server/docker/Dockerfile.android.ndk25-env
- server/src/main/java/com/defold/extender/services/RealGradleService.java
- server/src/main/resources/template.build.gradle
* Add standalone jetifier to Android docker image
* When resolve Gradle dependencies run standalone jetifier according to flag `useJetifier`.
P.S. Based on `split-docker` branch.
Fixes #301
> Run standalone jetifier if needed

- server/build.gradle
- server/configs/application-local-dev-app.yml
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/remote/RemoteEngineBuilder.java
- server/src/main/java/com/defold/extender/remote/RemoteHostConfiguration.java
- server/src/main/java/com/defold/extender/remote/RemoteInstanceConfig.java
- server/src/main/java/com/defold/extender/services/GCPInstanceService.java
- server/src/main/java/com/defold/extender/services/HealthReporterService.java
- server/src/main/java/com/defold/extender/services/data/GCPInstanceState.java
- server/src/test/java/com/defold/extender/remote/RemoteEngineBuilderTest.java
* Added new service that implements VM state management.
* Add new endpoint to set maintenance mode (update last used timestamp to prevent VMs from suspending/resuming VMs if it was suspended)
General implementation:
* At startup service look over extender.service.remote-builder.platforms and form maps with instance name and update last "touched" timestamp
* According to last "touched" timestamp and configured `extender.gcp.controller.time-before-suspend` service checks every `extender.gcp.controller.check-period` do VM need to be suspended.
* Before every request to remote builder we invoke `GCPInstanceService.touchInstance` to update last "touched" timestamp
Example of configuration:
```yml
extender:
gcp:
controller:
enabled: true
project_id: ${project_id}
zone: ${vm_zone}
wait-timeout: …
```
> Add GCPInstanceService which used to monitor and suspend gcp instances if instance not used for a while.

- server/src/main/java/com/defold/extender/cache/GCPDataCache.java
Fix issue when one of precondition was failed during cache entry upload due to concurrency from the side of other jobs.
```
Caused by: com.google.api.client.http.HttpResponseException: 412 Precondition Failed 
PUT https://storage.googleapis.com/upload/storage/v1/b/************/o?ifGenerationMatch=*************
{ 
"error": { 
"code": 412, 
"message": "At least one of the pre-conditions you specified did not hold.", 
"errors": [ 
{ 
"message": "At least one of the pre-conditions you specified did not hold.", 
"domain": "global", 
"reason": "conditionNotMet", 
"locationType": "header", 
"location": "If-Match" 
} 
] 
} 
} 
```
Now we catch and skip exception because it safe to continue because other job already uploaded the same cache entry.
> Fix cache issue

- server/src/main/java/com/defold/extender/ExtenderController.java
During debugging from VSCode I caught exception when request to `/job_status` and `/job_result` leads to Internal server error. It happened because Spring boot changed logic now doesn't parse argument name from bytecode. 
I don't know exactly why t works when Extender runs from command-line...
> Explicitly set parameter name.

- server/docker/common-services.yml
- server/manifestmergetool/build.gradle
Remove file-to-file bind.
Copy manifestmergetool directrly to ./server/app.
Seems on Windows something works in different way when use file bind.
Fixes #473
> Remove file-to-file bind

- server/docker/common-services.yml
- server/scripts/standalone/service-standalone.sh
If tried to build project with lots of source file (native part) you can get `400 Bad request` on `/build_async` request. It happened because Jetty has option `maxFormPart` that didn't respect in previous versions. With additional logging on Jetty side (options `-Dlogging.level.org.eclipse.jetty=DEBUG -Dlogging.level.org.eclipse.jetty.websocket=DEBUG`) following error become visible
```
2024-10-03 17:45:34 Caused by: org.eclipse.jetty.http.BadMessageException: 400: bad multipart
2024-10-03 17:45:34     ... 118 common frames omitted
2024-10-03 17:45:34 Caused by: java.lang.IllegalStateException: Form with too many keys [1001 > 1000]
2024-10-03 17:45:34     at org.eclipse.jetty.http.MultiPart$Parser.parse(MultiPart.java:1052)
2024-10-03 17:45:34     at …
```
> Add maxFormPart configuration option for Jetty.

- server/envs/generate_user_env.sh
> Remove old user.env during generation to avoid variable duplication.

- client/src/main/java/com/defold/extender/client/ExtenderClient.java
- server/README.md
- server/build.gradle
- server/configs/application-local-dev-app.yml
- server/configs/application-local-dev.yml
- server/configs/application-logging.yml
- server/configs/application-metrics.yml
- server/configs/extender-logging.xml
- server/docker/common-services.yml
- server/docker/docker-compose.yml
- server/scripts/standalone/service-standalone.sh
- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/TemplateExecutor.java
- server/src/main/java/com/defold/extender/log/Markers.java
- server/src/main/java/com/defold/extender/remote/RemoteEngineBuilder.java
- server/src/main/java/com/defold/extender/services/DataCacheService.java
- server/src/main/java/com/defold/extender/services/DefoldSdkService.java
- server/src/main/java/com/defold/extender/services/GCPInstanceService.java
- server/src/main/java/com/defold/extender/services/HealthReporterService.java
- server/src/main/java/com/defold/extender/services/RealGradleService.java
- server/src/main/java/com/defold/extender/tracing/ExtenderExecutor.java
- server/src/main/java/com/defold/extender/tracing/ExtenderTracerInterceptor.java
- server/src/main/java/com/defold/extender/tracing/TraceIdInResponseServletFilter.java
- server/src/main/resources/application.yml
* Add functionality to trace workload in distributed system. Now logs has `traceId` and `spanId`. By `traceId` it can be searched all logs related to build request.
* Add logging markers. It helps to categorize errors into several groups.
* Add example of config for structured logging.
* Extender client now can read `traceId` from response header.
Fixes #494 
Example of structured logging:
```
2024-10-09 18:03:37 {"@timestamp":"2024-10-09T15:03:37.512892758Z","@version":"1","message":"Schedule user credentials update","logger_name":"com.defold.extender.services.UserUpdateService","thread_name":"extenderTaskExecutor-1","level":"INFO","level_value":20000,"traceId":"ad11812defd201b5fb6f362eab5a4d7a","spanId":"e5d0e34b41651215"}
2024-10-09 18:03:37 …
```
> Improve logging

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
Podfile.lock now return as part of build result. Podfile.lock is located in `<project_root>/build/arm64-ios/` or `<project_root>/build/x86_64-ios/`
Fixes #470
> Add Podfile.lock to build results

- server/src/main/java/com/defold/extender/log/ExtenderLogEnhancer.java
- server/src/main/java/com/defold/extender/log/ExtenderLogEnhancerConfiguration.java
Custom log enhancer allows to add more fields to LogEntry that pushed to Stackdriver. It's useful in case when external instances pushes some logs to GCP.
Example how to configure Stackdriver appender:
```xml
<appender name="STACKDRIVER_CUSTOM" class="com.google.cloud.spring.logging.LoggingAppender">
<log>${STACKDRIVER_LOG_NAME}</log> 
<loggingEventEnhancer>com.google.cloud.spring.logging.TraceIdLoggingEnhancer</loggingEventEnhancer>
<loggingEventEnhancer>com.defold.extender.log.ExtenderLogEnhancer</loggingEventEnhancer>
<flushLevel>${STACKDRIVER_LOG_FLUSH_LEVEL}</flushLevel> 
</appender>
```
How it looks like in Cloud logging
> Add custom log enhancer to add more information to GCP LogEntry.

- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/tracing/ExtenderExecutor.java
To achieve sharing `traceId` and `spanId` across different thread's context custom task executor was implemented. By default it creates thread pool with size = 1.
```
A standard implementation of Spring's TaskScheduler interface, wrapping a native java.util.concurrent.ScheduledThreadPoolExecutor and providing all applicable configuration options for it. The default number of scheduler threads is 1; a higher number can be configured through setPoolSize.          <------------------------
This is Spring's traditional scheduler variant, staying as close as possible to java.util.concurrent.ScheduledExecutorService semantics. Task execution happens on the scheduler thread(s) rather than on separate execution threads. As a consequence, a ScheduledFuture handle (e.g. from schedule(Runnable, …
```
> Make custom thread pool size configurable.

- server/src/main/java/com/defold/extender/PlatformConfig.java
Some fields in `PlatformConfig` were initialized with empty string. That led to replace `symbolCmd` value with empty string during context's merging.
Example (how it was):
```
common.symbolCmd = ""
osx.symbolCmd = "dsymutil -o {{src}}.dSYM {{src}}"
arm64-osx.symbolCmd = ""
```
And as result `symbolCmd == ""`. If fields initially will be `null` - value of the field won't be replaced.
Example (how it will work after fix):
```
common.symbolCmd = null
osx.symbolCmd = "dsymutil -o {{src}}.dSYM {{src}}"
arm64-osx.symbolCmd = null
```
----> `symbolCmd = "dsymutil -o {{src}}.dSYM {{src}}"`
Fixes #330
> Fix replace symbolCmd with empty string when merge contexts.

- server/src/main/java/com/defold/extender/remote/RemoteEngineBuilder.java
- server/src/test/java/com/defold/extender/IntegrationTest.java
- server/test-data/ext_error_extension/ext.manifest
- server/test-data/ext_error_extension/src/test_error_ext.cpp
* Compilation error from remote builder now writes directly to result file without pushing it to logs.
* Add `consumeQuite` to make sure that response entity was fully consumed. Add test to check compilation error.
* Add async build variant to integration test configuration.
Fixes #550
> Rework compilation errors handling

- server/src/main/java/com/defold/extender/services/GCPInstanceService.java
- server/src/main/java/com/defold/extender/services/HealthReporterService.java
Check if instance in suspending state when health_report request is arrived. If instance in state other than suspended/suspending/running - return unreachable.
Possible issue: /health_report request arrived when one of the remote builder was in SUSPENDING state. It led to make a HTTP request to instance. But suspended instance didn't respond and didn't abort. Only one thing that I current don't understand is why configured HTTP timeouts didn't triggered?
> Improve health_report implementation

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ExtenderUtil.java
- server/src/test/java/com/defold/extender/ExtenderTest.java
- server/test-data/sdk/a/defoldsdk/extender/build.yml
Main part of the fix: https://github.com/defold/defold/pull/9756.
Added additional check if File is directory for case when we want collect only files. For collection osx/ios frameworks separate utility function was created because frameworks is directories.
Fixes #452
> Collect only files when Extender search for libraries.

- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/cache/GCPDataCache.java
The root cause is long-running cache operation. While Extender is uploading cached files to google bucket - remote build can be completed and removed job directory. It leads to exception like "file not found".
* Move upload caching before build start.
* Implement cache entry touch for google bucket implementation.
Fixes #549
> Fix exception during upload caching

- client/src/main/java/com/defold/extender/client/ExtenderClient.java
- client/src/main/java/com/defold/extender/client/ExtenderClientCache.java
- client/src/main/java/com/defold/extender/client/FileExtenderResource.java
- client/src/test/java/com/defold/extender/client/ExtenderClientTest.java
- server/src/main/java/com/defold/extender/services/HealthReporterService.java
* Possible problem was that response for `/query` returns HTTP error and Extender doesn't consume response stream.
* Replace `DefaultHttpClient` with preconfigured http client.
* Http client now stop sending request body if server returns one of 4XX code (https://lists.apache.org/thread/p38b3lrjt4vhyqthwhqcq3vsx3dpr3wj)
* Remove ExtenderClient constructor which accepts http client as argument.
* Add traceId to log file.
* Improve log file content in case of non-compilation error.
Fixes #528
> Consume http response in case of HTTP error

- server/build.gradle
- server/docker/docker-compose.yml
- server/scripts/start-test-server.sh
- server/src/test/java/com/defold/extender/AuthenticationTest.java
- server/src/test/java/com/defold/extender/ExtenderTest.java
- server/src/test/java/com/defold/extender/ExtenderUtilTest.java
- server/src/test/java/com/defold/extender/ExtensionManifestValidatorTest.java
- server/src/test/java/com/defold/extender/IntegrationTest.java
- server/src/test/java/com/defold/extender/TemplateExecutorTest.java
- server/src/test/java/com/defold/extender/ZipUtilsTest.java
- server/src/test/java/com/defold/extender/cache/CacheKeyGeneratorTest.java
- server/src/test/java/com/defold/extender/cache/DummyDataCacheTest.java
- server/src/test/java/com/defold/extender/cache/LocalDiskDataCacheTest.java
- server/src/test/java/com/defold/extender/cache/info/CacheInfoFileParserTest.java
- server/src/test/java/com/defold/extender/cache/info/CacheInfoFileWriterTest.java
- server/src/test/java/com/defold/extender/remote/RemoteEngineBuilderTest.java
- server/src/test/java/com/defold/extender/services/CocoaPodsServiceTest.java
- server/src/test/java/com/defold/extender/services/DefoldSDKServiceTest.java
- server/src/test/resources/junit-platform.properties
* Migrated test classes to JUnit5.
* Made changes to docker compose to eliminate collision between `AuthentificationTest` and `IntegrationTest`. Now two sets of docker containers can be run in parallel.
* Avoid shared resources between test cases (shared folders, etc.)
For local execution 
```
./gradlew :server:test --info
```
on my Mac (Apple M3 Pro, 36 GB) 
took
|Single thread|Parallel|Diff|
|-------------|-------|----|
|56m 12s       |16m 6s|-71.35%|
Fixes #565
> Migrate server tests to JUnit5

- server/src/main/java/com/defold/extender/builders/CSharpBuilder.java
Verified that the Dotnet 9 issue https://github.com/dotnet/runtime/issues/109341 was fixed for macOS, iOS and Android.
> Removed temporary hack for Dotnet 9 prerelease version

- server/docker/common-services.yml
- server/scripts/start-test-server.sh
- server/scripts/stop-test-server.sh
- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/ExtenderController.java
- server/src/main/java/com/defold/extender/ProcessExecutor.java
- server/src/main/java/com/defold/extender/services/DefoldSdkService.java
- server/src/main/java/com/defold/extender/services/data/DefoldSdk.java
- server/src/test/java/com/defold/extender/IntegrationTest.java
- server/src/test/java/com/defold/extender/services/DefoldSDKServiceTest.java
PR fixed various issues that poped-up after enable parallel tests execution. All issues were related to how Extender works with defold sdk.
Following issues were resolved:
1. Shared host folder with defold sdks for docker containers that used for testing.
2. Only one task for downloading scheduled when concurrent build job requests the same sdk that doesn't exist at the filesystem.
3. Fix issue with premature defold sdk folder cleanup when one or more build job that used that sdk are in progress.
More comments see in the code.
Fixes #375 
P.S. During local testing a couple of times I faced issue with process start (gradle/compiler/linker). Let's see how it goes when tests runs on CI.
> Fix concurrency issues with DefoldSdkService

- server/src/main/java/com/defold/extender/WebSecurityConfig.java
It was lots of deprecation warning about `authorizeRequests` (marked as for removal in Spring security 7.x).
> Update deprecated methods in WebSecurity

- server/src/main/java/com/defold/extender/services/DefoldSdkService.java
- server/src/main/resources/application.yml
- server/src/test/java/com/defold/extender/services/DefoldSDKServiceTest.java
Move sdk url patterns and mappings url patterns to application configuration. It allows to configure application in more flexible way.
Use cases:
1. If we want to move buckets with defoldsdks to other place (url will change).
2. End user wants to cache defoldsdk on own side. So user can configure custom address of caching proxy which return defoldsdk if it was cached or requests it from other location and cache it.
> Move sdk urls to application configuration

- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
Now module map and swift header generates every time except of cases when:
1. Pod spec has "module_map" == "false" or
2. Pod spec has "module_map" == "<path_to_module_map>"
According to https://guides.cocoapods.org/syntax/podspec.html#module_map default value is "true"
Fixes https://github.com/defold/extension-ironsource/issues/36
> Fix swift compilation

- server/src/main/java/com/defold/extender/ExtenderUtil.java
- server/src/main/java/com/defold/extender/services/DefoldSdkService.java
- server/src/main/resources/application.yml
- server/src/test/java/com/defold/extender/services/DefoldSDKServiceTest.java
Implement in-memory caching for platform mappings. The size of cache can be configured via `extender.sdk.mappings-cache-size` property. Concurrent downloading of mappings implements in the same manner as it was done for sdk downloading.
Fixes #553
> Cache sdk mappings

- server/src/main/java/com/defold/extender/services/DefoldSdkService.java
HEAD request return 301 that didn't handle properly. As result build failed with "defold sdk not found" error. Now GET and HEAD requests follow all redirects and work as expected.
> Fix HEAD request which checks defold sdk existence now correctly follow redirects

- server/scripts/standalone/setup-standalone-env.sh
Xcode toolchain now packs with `llbuild.framework` which used by `swift-driver`
Fixes #327 
Related https://github.com/defold/defold/pull/10105
> Update setup env script according to new xcode toolchain structure

- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/services/GradleService.java
- server/src/main/java/com/defold/extender/services/GradleServiceInterface.java
- server/src/main/java/com/defold/extender/services/MockGradleService.java
- server/src/main/java/com/defold/extender/services/RealGradleService.java
- server/src/main/resources/template.build.gradle
Android builds will send back a `gradle.lockfile` which contains output from gradle while resolving dependencies ([format](https://docs.gradle.org/current/userguide/dependency_locking.html#structure_of_lock_files)).
Example:
```
androidx.annotation:annotation-experimental:1.1.0=releaseRuntimeClasspath
androidx.annotation:annotation-jvm:1.6.0=releaseRuntimeClasspath
androidx.annotation:annotation:1.6.0=releaseRuntimeClasspath
androidx.arch.core:core-common:2.1.0=releaseRuntimeClasspath
androidx.arch.core:core-runtime:2.1.0=releaseRuntimeClasspath
androidx.asynclayoutinflater:asynclayoutinflater:1.0.0=releaseRuntimeClasspath
androidx.browser:browser:1.4.0=releaseRuntimeClasspath
androidx.collection:collection:1.1.0=releaseRuntimeClasspath …
```
> Send gradle log to client

- server/build.gradle
- server/src/main/java/com/defold/extender/ProcessExecutor.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
I reverted changes that was done in https://github.com/defold/extender/pull/611.
Now modulemap generated in case if no predefined modulemap found or if swift code is presented. In case if user uses framework with precompiled library with modulemap and without other source code - no need to generate and use additional modulemap.
Also reverted back GCP dependencies because it conflict with OpenTelemetry dependency.
Fixes #653
> Fix modulemap generation

- .github/workflows/docker-env-build.yml
With the latest version there was a segmentation fault during `apt-get install` step.
More info https://github.com/tonistiigi/binfmt/issues/240
> Fix qemu version

- server/src/main/java/com/defold/extender/services/RealGradleService.java
The build result will now include a Gradle dependency tree (`gradle.dependencytree`). This visualization of the dependency tree can be used to figure out how a transitive dependency was included in the final application bundle.
Fixes #647 
Example output from `extension-gpgs`:
```
gradle dependencies --configuration releaseCompileClasspath
> Task :dependencies
------------------------------------------------------------
Root project 'job16439745094295468761'
------------------------------------------------------------
releaseCompileClasspath - Resolved configuration for compilation for variant: release
+--- com.google.android.gms:play-services-base:18.5.0
|    +--- androidx.collection:collection:1.0.0 -> 1.1.0
|    |    \--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    +--- …
```
> Generate a Gradle dependency tree for Android builds

- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/ExtensionManifestValidator.java
Flag `-fdebug-compilation-dir` was set by compiler to current working dir. Now we use that flag to prefix source path in the debug information. Value for that flag takes from appmanifest (the same as we do for build variant, withSymbols flag, etc.)
Fixes #259
> Added flags for debug source remapping

- server/src/main/java/com/defold/extender/cache/GCPDataCache.java
- server/src/main/java/com/defold/extender/services/DataCacheService.java
In that PR only uploading issue is solved.
Before start uploading we add key to special set to synchronize operations between several threads.
The second issue with concurrent download/update will be solved on GCS bucket configuration's side.
Fixes #690
> Fixed issue with open sockets in case of cache upload fail

- server/configs/application-standalone-dev.yml
- server/src/main/java/com/defold/extender/AsyncBuilder.java
- server/src/main/java/com/defold/extender/Extender.java
- server/src/main/java/com/defold/extender/FrameworkUtil.java
- server/src/main/java/com/defold/extender/builders/CSharpBuilder.java
- server/src/main/java/com/defold/extender/process/ProcessExecutor.java
- server/src/main/java/com/defold/extender/process/ProcessUtils.java
- server/src/main/java/com/defold/extender/services/CocoaPodsService.java
- server/src/main/java/com/defold/extender/services/RealGradleService.java
- server/src/main/resources/application.yml
- server/src/test/java/com/defold/extender/AuthenticationTest.java
- server/src/test/java/com/defold/extender/IntegrationTest.java
* Implemented pod cache location configuration.
* Implemented pod cache cleanup.
* Implemented spec repo update according to schedule.
* Extract 'execCommand' to common utility class.
* Make CocoapodsService optional.
Cache rotation implmeneted via setting environment variable `CP_HOME_DIR`. According to the schedule service generates new value for that variable and start working with it. All previous cache location stored in the separate file. Scheduled task runs, read that file and remove all unused directories.
That approach helps to control cache size + it can fix issue with downloading specs (because we change directory and spec repository downloads again).
Also scheduled task will update spec repository. Probably it helps to avoid rate limit issues.
Fixes #344 
Possible fix for #680
> Rotate Cocoapods cache

- server/src/main/java/com/defold/extender/services/cocoapods/PodSpecParser.java
- server/src/test/java/com/defold/extender/services/cocoapods/CocoaPodsServiceTest.java
- server/test-data/pod_specs/PubNub.json
- server/test-data/pod_specs/TPNiOS.json
- server/test-data/pod_specs/Wilddog.json
`vendored_frameworks` can has values with bracers notation like `"core/AnyThink{Banner,Splash,RewardedVideo,Interstitial,Native,MediaVideo}.xcframework"` which should interpret as list of paths. So added bracers expand logic for different spec's files which contains paths. 
Applied the same logic for source paths, header paths, resource, frameworks and weak frameworks.
Also applied logic from #695 to compiler flags.
Based on https://github.com/defold/extender/tree/issue-684-pod-spec-parsing to avoid conflicts.
Fixes #686
> Fix cocoapods vendored framework parsing

- server/src/main/java/com/defold/extender/Extender.java
Partially rollback changes because older engine's version (before 1.10.12) don't pack resource bundles from pods into result ipa which can leads to issues with build submission to AppStore.
> Collect PrivacyInfo from pods for backward compatability

- .github/workflows/code-coverage.yml
- server/build.gradle
- server/src/test/java/com/defold/extender/AuthenticationTest.java
- server/src/test/java/com/defold/extender/IntegrationTest.java
Added JaCoCo code coverage report. Workflow runs on PR which targeted to `dev`. Generates 2 types of report: html (see screenshot) and markdown for Github (see comments)
> Added code coverage workflow
